### PR TITLE
debug #018 4sum

### PR DESCRIPTION
**Pull request by NgWilli**
"m < len" will cause assertion failed in exact input ,say (0,4,4,4,4,4,4,4,4)

### CODE REVIEW

**Comment by illuz** [comment]
You're right.

**Comment by NgWilli** [comment]
Glad to work with you! I'm new here and I just start kicking leetcode. Wish I could always consult with you!

**Comment by illuz** [comment]
Of course!

**Comment by NgWilli** [comment]
:)

**Pull request merged**
